### PR TITLE
Use scm instead of build/run

### PR DESCRIPTION
**Pull request by radimch**
Current build's scm is not always the one we want the decorator from

description is in
https://github.com/jenkinsci/forensics-api-plugin/pull/245

### CODE REVIEW

**Comment by uhafner** [comment]
See also an initial test case for the general problem: https://github.com/jenkinsci/git-forensics-plugin/pull/213

**Comment by uhafner** [comment]
See also https://issues.jenkins.io/browse/JENKINS-64578

**Comment by uhafner** [comment]
I merged that part now in #213. This PR still is a work in progress because I want to update the other elements as well. I johle it is ok if I publish all those changes in a single PR.

**Comment by radimch** [comment]
great, tnx!

**Pull request closed without merging**
